project:
  type: website
  output-dir: output

author:
  - name: Stefan Bringuier
    affiliations:
      - name: My Affiliation
        department: Group
        address: Where
        city: City
        country: USA
        postal-code: 00000
    orcid: 0000-0001-6753-1437
    email: stefanbringuier@gmail.com
    url: https://stefanbringuier.info

bibliography: _references/references.bib
